dataset:
  subsets: [spring, winter]

splitters:
  KFold:
    type: KFold
    n_splits: 5
    shuffle: true
    random_state: 42
  Random:
    type: ShuffleSplit
    n_splits: 5
    test_size: 0.2
    random_state: 42

models:
  RandomForestRegressor:
    class: sklearn.ensemble.RandomForestRegressor
    parameters:
      random_state: 42
      n_jobs: 1
    grid:
      n_estimators: [10, 50, 100, 250, 400]
      max_depth: [5, 10, 30, 50, 150, 200, null]
  KNeighborsRegressor:
    class: sklearn.neighbors.KNeighborsRegressor
    parameters:
      n_jobs: 1
    grid:
      n_neighbors: [3, 5, 10]
      weights: [uniform, distance]
      p: [1, 2]
      leaf_size: [10, 15, 30]
      metric: [minkowski, euclidean]

evaluation:
  metrics: [rmse, r_squared]
  refit: rmse
  workers: -1
