vars:
  - path:
      scripts: ../../src/datasets/logatec
      common: ../../src
      benchmarking: ../../src/benchmarking
      data: ../../artifacts/Scalability/data
      models: ../../artifacts/Scalability/models
      reports: ../../artifacts/Scalability/reports

  - subsets: [winter, spring]

stages:
  prepare:
    matrix:
      subset: ${subsets}
    cmd: |
      unzip -o -j ${path.data}/raw/logatec.zip ${item.subset}_data.json -d ${path.data}/raw/
      python ${path.benchmarking}/wrapper.py --output ${path.reports}/usage/prepare-${item.subset}_usage.pkl -- python ${path.scripts}/prepare.py --method average --input ${path.data}/raw/${item.subset}_data.json --output ${path.data}/base/${item.subset}.pkl
      rm ${path.data}/raw/${item.subset}_data.json
    deps:
      - ${path.scripts}/prepare.py
      - ${path.benchmarking}/wrapper.py
      - ${path.benchmarking}/performance.py
      - ${path.data}/raw/logatec.zip
    outs:
      - ${path.data}/base/${item.subset}.pkl

  scale:
    matrix:
      subset: ${subsets}
    cmd: >
      python ${path.benchmarking}/scale.py
      --factor "$SCALE_FACTOR"
      --input ${path.data}/base/${item.subset}.pkl
      --output ${path.data}/interim/${item.subset}.pkl
    deps:
      - ${path.benchmarking}/scale.py
      - ${path.data}/base/${item.subset}.pkl
    outs:
      - ${path.data}/interim/${item.subset}.pkl

  featurize:
    matrix:
      subset: ${subsets}
    cmd: >
      python ${path.benchmarking}/wrapper.py --output ${path.reports}/usage/featurize-${item.subset}_usage.pkl -- python ${path.scripts}/featurize.py
      --input ${path.data}/interim/${item.subset}.pkl
      --output ${path.data}/prepared/${item.subset}.pkl
    deps:
      - ${path.scripts}/featurize.py
      - ${path.benchmarking}/wrapper.py
      - ${path.benchmarking}/performance.py
      - ${path.data}/interim/${item.subset}.pkl
    outs:
      - ${path.data}/prepared/${item.subset}.pkl

  split:
    matrix:
      subset: ${subsets}
      split: ${split.types}
    cmd: >
      python ${path.benchmarking}/wrapper.py --output ${path.reports}/usage/split-${item.subset}-${item.split}_usage.pkl -- python ${path.scripts}/split.py
      --input ${path.data}/prepared/${item.subset}.pkl
      --split ${item.split}
      --output-indices ${path.data}/splits/${item.subset}-${item.split}Split.pkl
    deps:
      - ${path.scripts}/split.py
      - ${path.benchmarking}/wrapper.py
      - ${path.benchmarking}/performance.py
      - ${path.data}/prepared/${item.subset}.pkl
    outs:
      - ${path.data}/splits/${item.subset}-${item.split}Split.pkl

  gridsearch:
    matrix:
      subset: ${subsets}
      split: ${split.types}
      model: ${gridsearch}
    cmd: >
      python ${path.benchmarking}/wrapper.py --output ${path.reports}/usage/gridsearch-${item.subset}-${item.split}-${item.model}_usage.pkl -- python ${path.common}/benchmark.py
      --use ${item.model}
      --optimizer gridsearch
      --data ${path.data}/prepared/${item.subset}.pkl
      --split-indices ${path.data}/splits/${item.subset}-${item.split}Split.pkl
      --output-results ${path.models}/gridsearch-${item.subset}-${item.split}-${item.model}/${item.subset}-${item.model}-${item.split}Split-results.pkl
    deps:
      - ${path.common}/benchmark.py
      - ${path.benchmarking}/wrapper.py
      - ${path.benchmarking}/performance.py
      - ${path.data}/prepared/${item.subset}.pkl
      - ${path.data}/splits/${item.subset}-${item.split}Split.pkl
    outs:
      - ${path.models}/gridsearch-${item.subset}-${item.split}-${item.model}/${item.subset}-${item.model}-${item.split}Split-results.pkl

  automl:
    matrix:
      subset: ${subsets}
      split: ${split.types}
      model: ${automl}
    cmd: >
      python ${path.benchmarking}/wrapper.py --output ${path.reports}/usage/automl-${item.subset}-${item.split}-${item.model}_usage.pkl -- python ${path.common}/benchmark.py
      --use ${item.model}
      --optimizer automl
      --data ${path.data}/prepared/${item.subset}.pkl
      --split-indices ${path.data}/splits/${item.subset}-${item.split}Split.pkl
      --output-results ${path.models}/automl-${item.subset}-${item.split}-${item.model}/${item.subset}-${item.model}-${item.split}Split-results.pkl
    params:
      - automl.${item.model}
    deps:
      - ${path.common}/benchmark.py
      - ${path.benchmarking}/wrapper.py
      - ${path.benchmarking}/performance.py
      - ${path.data}/prepared/${item.subset}.pkl
      - ${path.data}/splits/${item.subset}-${item.split}Split.pkl
    outs:
      - ${path.models}/automl-${item.subset}-${item.split}-${item.model}/${item.subset}-${item.model}-${item.split}Split-results.pkl
